#!/bin/bash

usage(){
	echo "$(tput bold ; tput setaf 6) Usage $0 [number of loop] '[string]'"
	echo "Dont forget to protect string with quotes $(tput sgr0)"
	exit
}

footer(){
	echo -e "\n$(tput setaf 6) CykloDev $(tput setaf 7)pl$(tput setaf 2)3$(tput setaf 7)dg$(tput setaf 2)3$(tput setaf 7) th$(tput setaf 2)3 3$(tput setaf 7)dg$(tput setaf 2)3 \n" 
}

if [ -z ${1} ] || [ -z ${2}] 
then
	usage
fi

function dec(){
	uncompress=`printf %s $data | base64 -di | gunzip` 2>/dev/null
	base64_raw=`printf %s "$uncompress==" | base64 -di` 2>/dev/null
	val=$(printf %s "$base64_raw" | sed 's/.\{3\}/&\\/g' )
	full_val=\\${val%?}
	#printf %s  "--> $full_val"
	#echo ""
	hex_val=$(printf "$full_val")
	#printf %s "--> $hex_val"
	#echo ""
	data=$hex_val
}

data=$2
loop=$1

count=0;
while [[ $count -lt $loop  ]]
do
        echo "$(tput setaf 1)### Loop $count$(tput setaf 4)"
        dec "$data" 2>/dev/null
        printf %s $data
        echo "$(tput sgr0)"
        ((count++))
done

footer
